CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" text,
  "email" text,
  "hashed_password" text,
  "is_active" boolean,
  "is_superuser" boolean
);

CREATE TABLE "entry" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "creation_date" timestamp DEFAULT NOW() not NULL,
  "user" int NOT NULL,
  "title" text,
  "description" text,
  "value" numeric(10, 2),
  "operation_date" timestamp,
  "operation_type" int NOT NULL,
  "planned_entry" int
);

CREATE TABLE "operation_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text
);

CREATE TABLE "planned_entry" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "creation_date" timestamp DEFAULT NOW() not NULL,
  "user" int NOT NULL,
  "title" text,
  "description" text,
  "value" numeric(10, 2),
  "operation_date" timestamp,
  "operation_type" int NOT NULL,
  "installments_num" int
);

ALTER TABLE "entry" ADD FOREIGN KEY ("user") REFERENCES "user" ("id");
ALTER TABLE "entry" ADD FOREIGN KEY ("operation_type") REFERENCES "operation_type" ("id");
ALTER TABLE "entry" ADD FOREIGN KEY ("planned_entry") REFERENCES "planned_entry" ("id");
ALTER TABLE "planned_entry" ADD FOREIGN KEY ("operation_type") REFERENCES "operation_type" ("id");
ALTER TABLE "planned_entry" ADD FOREIGN KEY ("user") REFERENCES "user" ("id");
